[project]
name = "sensory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tim Reddick", email = "tim.reddick@8451.com" }
]
requires-python = ">=3.13.2"
dependencies = []

[project.scripts]
sensory = "sensory:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
